### ISSUE TITLE
Unable to resolve the request "gii/giixModel".

### ISSUE THREAD

**Issue by larry-tx** [rcoelho/giix#15]
I've downloaded (actually cloned) giix from GitHub to my extensions directory and followed the installation instructions to the letter. At first I tried it without running the CPhpMessageSource.patch because comments seemed to suggest that the issue had been fixed. Then, I got the message "Unable to resolve the request "gii/giixModel" when trying to run GiixModel Generator.

I went back and applied the patch (although it took me quite a while to find CPhpMessageSource.php since I most definitely don't need the i18n functionality). I then tried to run GiixModel Generator again. Again, it gave me the error message Unable to resolve the request "gii/giixModel".

When I tried a "dry-run" on patch CPhpMessageSource.php, it returned the following message (which may be why the problem occurs):

```
$ patch -p0 --dry-run < CPhpMessageSource.patch
patching file CPhpMessageSource.php
Hunk #1 FAILED at 62.
Hunk #2 FAILED at 94.
2 out of 2 hunks FAILED -- saving rejects to file CPhpMessageSource.php.rej
```

Any suggestions on what I may be doing wrong or how I can get around this issue? This really looks like a wonderful extension. I would hope that the functionality would be incorporated into the Yii base soon.

**Comment by qiansen1386** [comment]
Same thing happened also. i removed the 1.9.1 directory and upgraded to 1.10. it is still the same. my concern is do we need a earlier version?

updated: the reason of it is because of caseSensitive=false form URLmanager. And XueQiang said the url manager will convert the whole url string to lowercase. but the gii won't do the same for actions so that gii will not be able to find the class. 

Some guys find out the same thing and one of them has suggested giix project manager to put this warning inside INSTALL file. but they never really do it. I think they probably forgot to put. and very few people faced this issue. And the caseSensitive=false is not recommended.
